### ISSUE TITLE
Is our "Fixer" class approach appropriate?

### ISSUE THREAD

**Issue by agstephens** [roocs/proto-lib-34e#9]
Please check whether the Fixer approach that we have implemented will be flexible enough to address all issues with CMIP5, CMIP6 and CORDEX data.

Use the ESMValTool repository to review examples of fixes that are needed. 

Do we need something more than: 
 - pre-processor
 - post-processor

**Comment by ellesmith88** [comment]
Currently can't see any issues that couldn't be fixed by either a pre-process or a post-process. However, CORDEX data isn't addressed in the ESMValTool so there are no examples of fixes for this as far as I'm aware.

**Comment by agstephens** [comment]
Let's close this and we can address issues as they arise.
